[package]
name = "folio-cli"
description = "Meety CLI for testing the core library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "folio-cli"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
meety-core = { path = "../meety-core" }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
whisper-rs = { workspace = true }
hound = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
