pub mod audio;
pub mod cloud_guard;
pub mod diarization;
pub mod encryption;
pub mod error;
pub mod live_notes;
pub mod llm;
pub mod mcp_server;
pub mod memory;
pub mod paths;
pub mod permissions;
pub mod qos;
pub mod recipes;
pub mod server;
pub mod speaker_memory;
pub mod storage;
pub mod text;
pub mod transcription;
pub mod user_profile;

pub use error::{MeetyError, Result};
