// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncState } from "./SyncState";

export type RecordingSummary = { session_dir: string, label: string, duration_seconds: bigint, mic_bytes: bigint | null, system_bytes: bigint | null, mic_sample_rate: number | null, system_sample_rate: number | null, created_at: string | null, has_transcript: boolean, suggested_title?: string | null, suggested_tags?: Array<string>, suggested_subtitle?: string | null, language_override?: string | null, title?: string | null, draft_name?: string | null, sync?: SyncState | null, };
