// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteStatus } from "./RemoteStatus";
import type { UploadPhase } from "./UploadPhase";

export type SyncState = { schema_version: number, recording_id: string, remote_recording_id?: string | null, remote_job_id?: string | null, upload_state: UploadPhase, remote_status: RemoteStatus, last_synced_at?: string | null, error?: string | null, };
